version: '3.7'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: i_api
    restart: always
    container_name: c_api
    command: /app/node_modules/.bin/nodemon index.js
    volumes:
      - ./api/:/app
      - ./api/node_modules:/app/node_modules
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
    depends_on:
      - database
    networks:
     - app-private-network
  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - data-volume:/data/db
    ports:
      - "5432:5432"
    networks:
      - app-private-network
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: client_image
    container_name: client_container
    command: npm start
    volumes:
      - ./client/:/app
      - ./client/node_modules:/app/node_modules
    stdin_open: true
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - app-private-network
networks:
    app-private-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local